application:
  domain: http://localhost:8080


validation:
  emailPattern: [a-z0-9!#$%&'*+\\/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+\\/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?
  passwordPattern: ^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$